-- 题库版本分类。事务与版本由 Flyway 管理。
-- IF NOT EXISTS 仅跳过已有对象，不修复已有表结构；结构变更须新增迁移。
CREATE TABLE IF NOT EXISTS edition (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL,
    name text NOT NULL,
    sort_order integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT edition_uk_1 UNIQUE (code),
    CONSTRAINT edition_ck_2 CHECK (btrim(code) <> ''),
    CONSTRAINT edition_ck_3 CHECK (sort_order > 0)
);

COMMENT ON TABLE edition IS '题库版本分类';
COMMENT ON COLUMN edition.id IS '数据库独立主键';
COMMENT ON COLUMN edition.code IS '版本代码，如 standard、campus';
COMMENT ON COLUMN edition.name IS '版本名称';
COMMENT ON COLUMN edition.sort_order IS '显示顺序，从 1 开始';
COMMENT ON COLUMN edition.created_at IS '创建时间';
COMMENT ON COLUMN edition.updated_at IS '更新时间，后续写入层负责更新';

