-- 试卷。事务与版本由 Flyway 管理。
-- IF NOT EXISTS 仅跳过已有对象，不修复已有表结构；结构变更须新增迁移。
CREATE TABLE IF NOT EXISTS exam_paper (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id bigint NOT NULL,
    test_no integer NOT NULL,
    slug text NOT NULL,
    title text NOT NULL,
    subtitle text NOT NULL DEFAULT '',
    duration_minutes integer,
    status text NOT NULL DEFAULT 'pending',
    edition_note text NOT NULL DEFAULT '',
    source_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT exam_paper_fk_1 FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE RESTRICT,
    CONSTRAINT exam_paper_uk_2 UNIQUE (book_id, test_no),
    CONSTRAINT exam_paper_uk_3 UNIQUE (slug),
    CONSTRAINT exam_paper_ck_4 CHECK (test_no > 0),
    CONSTRAINT exam_paper_ck_5 CHECK (btrim(slug) <> ''),
    CONSTRAINT exam_paper_ck_6 CHECK (duration_minutes IS NULL OR duration_minutes > 0),
    CONSTRAINT exam_paper_ck_7 CHECK (status IN ('pending', 'draft', 'published')),
    CONSTRAINT exam_paper_ck_8 CHECK (jsonb_typeof(source_metadata) = 'object')
);

COMMENT ON TABLE exam_paper IS '试卷';
COMMENT ON COLUMN exam_paper.id IS '数据库独立主键';
COMMENT ON COLUMN exam_paper.book_id IS '所属册';
COMMENT ON COLUMN exam_paper.test_no IS '册内试卷编号';
COMMENT ON COLUMN exam_paper.slug IS '稳定访问标识';
COMMENT ON COLUMN exam_paper.title IS '试卷标题';
COMMENT ON COLUMN exam_paper.subtitle IS '试卷副标题';
COMMENT ON COLUMN exam_paper.duration_minutes IS '考试时长，单位分钟';
COMMENT ON COLUMN exam_paper.status IS 'pending 待录入、draft 草稿、published 已发布';
COMMENT ON COLUMN exam_paper.edition_note IS '源内容版本说明';
COMMENT ON COLUMN exam_paper.source_metadata IS '原卷来源说明、页码和链接，不保存暂缓模块';
COMMENT ON COLUMN exam_paper.created_at IS '创建时间';
COMMENT ON COLUMN exam_paper.updated_at IS '更新时间，后续写入层负责更新';

