-- 试卷 Part。事务与版本由 Flyway 管理。
-- IF NOT EXISTS 仅跳过已有对象，不修复已有表结构；结构变更须新增迁移。
CREATE TABLE IF NOT EXISTS exam_section (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paper_id bigint NOT NULL,
    code text NOT NULL,
    part_no integer NOT NULL,
    title text NOT NULL,
    question_format text NOT NULL,
    paper_reference text NOT NULL DEFAULT '',
    expected_option_count integer,
    sort_order integer NOT NULL,
    source_groups jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT exam_section_fk_1 FOREIGN KEY (paper_id) REFERENCES exam_paper (id) ON DELETE RESTRICT,
    CONSTRAINT exam_section_uk_2 UNIQUE (paper_id, code),
    CONSTRAINT exam_section_uk_3 UNIQUE (paper_id, part_no),
    CONSTRAINT exam_section_uk_4 UNIQUE (paper_id, sort_order),
    CONSTRAINT exam_section_ck_5 CHECK (btrim(code) <> ''),
    CONSTRAINT exam_section_ck_6 CHECK (part_no BETWEEN 1 AND 7),
    CONSTRAINT exam_section_ck_7 CHECK (sort_order > 0),
    CONSTRAINT exam_section_ck_8 CHECK (expected_option_count IS NULL OR expected_option_count >= 0),
    CONSTRAINT exam_section_ck_9 CHECK (question_format IN ('multiple_choice_cloze', 'open_cloze', 'word_formation', 'key_word_transformation', 'reading_multiple_choice', 'gapped_text', 'multiple_matching')),
    CONSTRAINT exam_section_ck_10 CHECK (jsonb_typeof(source_groups) = 'array')
);

COMMENT ON TABLE exam_section IS '试卷 Part';
COMMENT ON COLUMN exam_section.id IS '数据库独立主键';
COMMENT ON COLUMN exam_section.paper_id IS '所属试卷';
COMMENT ON COLUMN exam_section.code IS '原 Part 标识，如 P1';
COMMENT ON COLUMN exam_section.part_no IS 'Part 编号，第一期为 1 至 7';
COMMENT ON COLUMN exam_section.title IS 'Part 标题';
COMMENT ON COLUMN exam_section.question_format IS '结构化题型代码';
COMMENT ON COLUMN exam_section.paper_reference IS '原卷出处';
COMMENT ON COLUMN exam_section.expected_option_count IS '源数据声明的选项数量';
COMMENT ON COLUMN exam_section.sort_order IS '试卷内显示顺序';
COMMENT ON COLUMN exam_section.source_groups IS '原文分组，paragraph_ids 引用本 Part 内 source_key，由保存层校验';
COMMENT ON COLUMN exam_section.created_at IS '创建时间';
COMMENT ON COLUMN exam_section.updated_at IS '更新时间，后续写入层负责更新';

