-- 单题或多题共用的选项组。事务与版本由 Flyway 管理。
-- IF NOT EXISTS 仅跳过已有对象，不修复已有表结构；结构变更须新增迁移。
CREATE TABLE IF NOT EXISTS option_set (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id bigint NOT NULL,
    code text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT option_set_fk_1 FOREIGN KEY (section_id) REFERENCES exam_section (id) ON DELETE RESTRICT,
    CONSTRAINT option_set_uk_2 UNIQUE (section_id, code),
    CONSTRAINT option_set_uk_3 UNIQUE (id, section_id),
    CONSTRAINT option_set_ck_4 CHECK (btrim(code) <> '')
);

COMMENT ON TABLE option_set IS '单题或多题共用的选项组';
COMMENT ON COLUMN option_set.id IS '数据库独立主键';
COMMENT ON COLUMN option_set.section_id IS '所属 Part';
COMMENT ON COLUMN option_set.code IS 'Part 内组标识，单题为 question-题号，共用为 shared';
COMMENT ON COLUMN option_set.created_at IS '创建时间';
COMMENT ON COLUMN option_set.updated_at IS '更新时间，后续写入层负责更新';

