-- 题目参考答案。事务与版本由 Flyway 管理。
-- IF NOT EXISTS 仅跳过已有对象，不修复已有表结构；结构变更须新增迁移。
CREATE TABLE IF NOT EXISTS question_answer (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id bigint NOT NULL,
    display_text text NOT NULL,
    raw_answer jsonb NOT NULL,
    accepted_answers text[],
    answer_status text NOT NULL,
    answer_source text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT question_answer_fk_1 FOREIGN KEY (question_id) REFERENCES question (id) ON DELETE RESTRICT,
    CONSTRAINT question_answer_uk_2 UNIQUE (question_id),
    CONSTRAINT question_answer_ck_3 CHECK (btrim(answer_status) <> ''),
    CONSTRAINT question_answer_ck_4 CHECK (
        CASE WHEN jsonb_typeof(raw_answer) = 'array'
            THEN NOT jsonb_path_exists(raw_answer, 'strict $[*] ? (@.type() != "string")')
            ELSE jsonb_typeof(raw_answer) = 'string'
        END
    )
);

COMMENT ON TABLE question_answer IS '题目参考答案';
COMMENT ON COLUMN question_answer.id IS '数据库独立主键';
COMMENT ON COLUMN question_answer.question_id IS '所属题目，每题最多一条答案记录';
COMMENT ON COLUMN question_answer.display_text IS '原参考答案展示文本，不按斜杠拆分';
COMMENT ON COLUMN question_answer.raw_answer IS '保留原答案字符串或字符串数组及其类型';
COMMENT ON COLUMN question_answer.accepted_answers IS '经核验的完整等价答案，未核验时为空';
COMMENT ON COLUMN question_answer.answer_status IS '原答案状态，official 仅代表源数据标注';
COMMENT ON COLUMN question_answer.answer_source IS '原答案出处';
COMMENT ON COLUMN question_answer.created_at IS '创建时间';
COMMENT ON COLUMN question_answer.updated_at IS '更新时间，后续写入层负责更新';
