-- 册。事务与版本由 Flyway 管理。
-- IF NOT EXISTS 仅跳过已有对象，不修复已有表结构；结构变更须新增迁移。
CREATE TABLE IF NOT EXISTS book (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edition_id bigint NOT NULL,
    book_no integer NOT NULL,
    title text NOT NULL,
    sort_order integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT book_fk_1 FOREIGN KEY (edition_id) REFERENCES edition (id) ON DELETE RESTRICT,
    CONSTRAINT book_uk_2 UNIQUE (edition_id, book_no),
    CONSTRAINT book_ck_3 CHECK (book_no > 0),
    CONSTRAINT book_ck_4 CHECK (sort_order > 0)
);

COMMENT ON TABLE book IS '册';
COMMENT ON COLUMN book.id IS '数据库独立主键';
COMMENT ON COLUMN book.edition_id IS '所属版本';
COMMENT ON COLUMN book.book_no IS '版本内册号';
COMMENT ON COLUMN book.title IS '册标题';
COMMENT ON COLUMN book.sort_order IS '显示顺序';
COMMENT ON COLUMN book.created_at IS '创建时间';
COMMENT ON COLUMN book.updated_at IS '更新时间，后续写入层负责更新';

