-- 原文段落及译文。事务与版本由 Flyway 管理。
-- IF NOT EXISTS 仅跳过已有对象，不修复已有表结构；结构变更须新增迁移。
CREATE TABLE IF NOT EXISTS passage_paragraph (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id bigint NOT NULL,
    source_key text NOT NULL,
    role text NOT NULL DEFAULT 'paragraph',
    text text NOT NULL,
    translation text NOT NULL DEFAULT '',
    sort_order integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT passage_paragraph_fk_1 FOREIGN KEY (section_id) REFERENCES exam_section (id) ON DELETE RESTRICT,
    CONSTRAINT passage_paragraph_uk_2 UNIQUE (section_id, source_key),
    CONSTRAINT passage_paragraph_uk_3 UNIQUE (section_id, sort_order),
    CONSTRAINT passage_paragraph_uk_4 UNIQUE (id, section_id),
    CONSTRAINT passage_paragraph_ck_5 CHECK (btrim(source_key) <> ''),
    CONSTRAINT passage_paragraph_ck_6 CHECK (role IN ('heading', 'paragraph', 'caption')),
    CONSTRAINT passage_paragraph_ck_7 CHECK (sort_order > 0)
);

COMMENT ON TABLE passage_paragraph IS '原文段落及译文';
COMMENT ON COLUMN passage_paragraph.id IS '数据库独立主键';
COMMENT ON COLUMN passage_paragraph.section_id IS '所属 Part';
COMMENT ON COLUMN passage_paragraph.source_key IS '源段落标识，仅在所属 Part 内唯一';
COMMENT ON COLUMN passage_paragraph.role IS 'heading 标题、paragraph 正文、caption 图注';
COMMENT ON COLUMN passage_paragraph.text IS '原文，保留换行及题号占位符';
COMMENT ON COLUMN passage_paragraph.translation IS '译文，未提供时为空字符串';
COMMENT ON COLUMN passage_paragraph.sort_order IS 'Part 内段落顺序';
COMMENT ON COLUMN passage_paragraph.created_at IS '创建时间';
COMMENT ON COLUMN passage_paragraph.updated_at IS '更新时间，后续写入层负责更新';

