-- 选项组内的选项。事务与版本由 Flyway 管理。
-- IF NOT EXISTS 仅跳过已有对象，不修复已有表结构；结构变更须新增迁移。
CREATE TABLE IF NOT EXISTS question_option (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option_set_id bigint NOT NULL,
    label text NOT NULL,
    content text NOT NULL,
    sort_order integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT question_option_fk_1 FOREIGN KEY (option_set_id) REFERENCES option_set (id) ON DELETE RESTRICT,
    CONSTRAINT question_option_uk_2 UNIQUE (option_set_id, label),
    CONSTRAINT question_option_uk_3 UNIQUE (option_set_id, sort_order),
    CONSTRAINT question_option_ck_4 CHECK (btrim(label) <> ''),
    CONSTRAINT question_option_ck_5 CHECK (sort_order > 0)
);

COMMENT ON TABLE question_option IS '选项组内的选项';
COMMENT ON COLUMN question_option.id IS '数据库独立主键';
COMMENT ON COLUMN question_option.option_set_id IS '所属选项组';
COMMENT ON COLUMN question_option.label IS '原选项标签，如 A';
COMMENT ON COLUMN question_option.content IS '原选项文字';
COMMENT ON COLUMN question_option.sort_order IS '组内显示顺序';
COMMENT ON COLUMN question_option.created_at IS '创建时间';
COMMENT ON COLUMN question_option.updated_at IS '更新时间，后续写入层负责更新';

