-- 题目与答案解析。事务与版本由 Flyway 管理。
-- IF NOT EXISTS 仅跳过已有对象，不修复已有表结构；结构变更须新增迁移。
CREATE TABLE IF NOT EXISTS question (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id bigint NOT NULL,
    question_no integer NOT NULL,
    sort_order integer NOT NULL,
    stem text NOT NULL,
    option_set_id bigint,
    question_type_label text NOT NULL,
    analysis text NOT NULL DEFAULT '',
    type_note text NOT NULL DEFAULT '',
    strategy text NOT NULL DEFAULT '',
    pitfall text NOT NULL DEFAULT '',
    solve_steps jsonb NOT NULL DEFAULT '[]'::jsonb,
    distractors jsonb NOT NULL DEFAULT '{}'::jsonb,
    knowledge jsonb,
    logic_links jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT question_fk_1 FOREIGN KEY (section_id) REFERENCES exam_section (id) ON DELETE RESTRICT,
    CONSTRAINT question_fk_2 FOREIGN KEY (option_set_id, section_id) REFERENCES option_set (id, section_id) ON DELETE RESTRICT,
    CONSTRAINT question_uk_3 UNIQUE (section_id, question_no),
    CONSTRAINT question_uk_4 UNIQUE (section_id, sort_order),
    CONSTRAINT question_uk_5 UNIQUE (id, section_id),
    CONSTRAINT question_ck_6 CHECK (question_no > 0),
    CONSTRAINT question_ck_7 CHECK (sort_order > 0),
    CONSTRAINT question_ck_8 CHECK (
        CASE WHEN jsonb_typeof(solve_steps) = 'array'
            THEN NOT jsonb_path_exists(solve_steps, 'strict $[*] ? (@.type() != "string")')
            ELSE false
        END
    ),
    CONSTRAINT question_ck_9 CHECK (jsonb_typeof(distractors) = 'object'),
    CONSTRAINT question_ck_10 CHECK (knowledge IS NULL OR jsonb_typeof(knowledge) = 'object'),
    CONSTRAINT question_ck_11 CHECK (jsonb_typeof(logic_links) = 'array')
);

CREATE INDEX IF NOT EXISTS idx_question_option_set_id ON question (option_set_id, section_id);

COMMENT ON TABLE question IS '题目与答案解析';
COMMENT ON COLUMN question.id IS '数据库独立主键';
COMMENT ON COLUMN question.section_id IS '所属 Part';
COMMENT ON COLUMN question.question_no IS '原题号；整卷题号完整性由发布层校验';
COMMENT ON COLUMN question.sort_order IS 'Part 内题目顺序';
COMMENT ON COLUMN question.stem IS '原题干，保留换行、关键词与空格';
COMMENT ON COLUMN question.option_set_id IS '同 Part 内选项组，无选项题为空';
COMMENT ON COLUMN question.question_type_label IS '原题型及知识点说明';
COMMENT ON COLUMN question.analysis IS '答案解析';
COMMENT ON COLUMN question.type_note IS '题型说明';
COMMENT ON COLUMN question.strategy IS '解题策略';
COMMENT ON COLUMN question.pitfall IS '易错点';
COMMENT ON COLUMN question.solve_steps IS '有序解题步骤字符串数组';
COMMENT ON COLUMN question.distractors IS '选项标签到排除理由的映射';
COMMENT ON COLUMN question.knowledge IS '题目级知识点对象，未提供时为 SQL NULL';
COMMENT ON COLUMN question.logic_links IS '题目级逻辑线索，内部引用由保存层校验';
COMMENT ON COLUMN question.created_at IS '创建时间';
COMMENT ON COLUMN question.updated_at IS '更新时间，后续写入层负责更新';
