-- 题目原文证据句。事务与版本由 Flyway 管理。
-- IF NOT EXISTS 仅跳过已有对象，不修复已有表结构；结构变更须新增迁移。
CREATE TABLE IF NOT EXISTS question_evidence (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id bigint NOT NULL,
    question_id bigint NOT NULL,
    paragraph_id bigint NOT NULL,
    quote text NOT NULL,
    sort_order integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT question_evidence_fk_1 FOREIGN KEY (question_id, section_id) REFERENCES question (id, section_id) ON DELETE RESTRICT,
    CONSTRAINT question_evidence_fk_2 FOREIGN KEY (paragraph_id, section_id) REFERENCES passage_paragraph (id, section_id) ON DELETE RESTRICT,
    CONSTRAINT question_evidence_uk_3 UNIQUE (question_id, sort_order),
    CONSTRAINT question_evidence_ck_4 CHECK (sort_order > 0)
);

CREATE INDEX IF NOT EXISTS idx_question_evidence_paragraph_id ON question_evidence (paragraph_id, section_id);

COMMENT ON TABLE question_evidence IS '题目原文证据句';
COMMENT ON COLUMN question_evidence.id IS '数据库独立主键';
COMMENT ON COLUMN question_evidence.section_id IS '题目与段落共同所属的 Part';
COMMENT ON COLUMN question_evidence.question_id IS '所属题目';
COMMENT ON COLUMN question_evidence.paragraph_id IS '原文段落';
COMMENT ON COLUMN question_evidence.quote IS '原证据引用文字，保留题号占位符';
COMMENT ON COLUMN question_evidence.sort_order IS '同题内证据顺序';
COMMENT ON COLUMN question_evidence.created_at IS '创建时间';
COMMENT ON COLUMN question_evidence.updated_at IS '更新时间，后续写入层负责更新';

